[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false
ffi = false

[fuzz]
runs = 1000
max_test_rejects = 100000

[invariant]
runs = 256
depth = 128
